### ISSUE TITLE
Problem during Parallel Processing: possible EventEmitter memory leak detected. 11 listeners added.

### ISSUE THREAD

**Issue by UzEE** [aheckmann/gm#186]
I'm using **gm** to process and optimize an image and resize it into 10 different sizes. Sizes are defined in an array and I use a `Array.forEach()` to iterate over each `size` and run the following on **gm**:

``` javascript
gm(image)
    .resize(size.width, size.height, "^")
    .crop(size.width, size.height, 0, 0)
    .minify(10)
    .noProfile()
    .compress('JPEG')
    .stream('jpg')
    .pipe(storageClient.upload(...));
```

The input `image` is a GET stream via **request** module. It is being shared over each iteration of the loop. This code is supposed to run on a background worker on Windows Azure but during testing on my development machine, I'm getting the following warning in the log:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.EventEmitter.addListener (events.js:160:15)
    at Request.Stream.pipe (stream.js:70:12)
    at Request.pipe (C:\users\uzair\documents\My Web Sites\node\PicSys\local_package.csx\roles\Processor\approot\node_modules\request\index.js:1176:34)
    at gm._spawn (C:\users\uzair\documents\My Web Sites\node\PicSys\local_package.csx\roles\Processor\approot\node_modules\gm\lib\command.js:210:25)
    at C:\users\uzair\documents\My Web Sites\node\PicSys\local_package.csx\roles\Processor\approot\node_modules\gm\lib\command.js:112:19
    at series (C:\users\uzair\documents\My Web Sites\node\PicSys\local_package.csx\roles\Processor\approot\node_modules\gm\node_modules\array-series\index.js:11:36)
    at gm._preprocess (C:\users\uzair\documents\My Web Sites\node\PicSys\local_package.csx\roles\Processor\approot\node_modules\gm\lib\command.js:149:5)
    at gm.stream (C:\users\uzair\documents\My Web Sites\node\PicSys\local_package.csx\roles\Processor\approot\node_modules\gm\lib\command.js:110:10)
    at C:\users\uzair\documents\My Web Sites\node\PicSys\local_package.csx\roles\Processor\approot\entities\users.js:153:8
    at Array.forEach (native)
```

`users.js` is the file in which my image processing code is running. 

I'm rather new to node, but from my research I found that this warning in thrown when a default limit of 10 listeners for a particular event is thrown. Is there a way in **gm** to work around this and increase the maximum number of listeners?

Thanks.

**Comment by gpolyn** [comment]
Having this issue (node 0.10, gm 1.17, express 4, async) where I can't see how I can adapt the above guidance for this usage...
```javascript
  gm(res).resize(ht, width, '^').gravity('Center').extent(ht, width).quality(80).stream(function(err, stdout, stderr) {
    if (err) {
      cb(err);
    } else {

      var buf = new Buffer(0);

      stdout.on('data', function(d) {
        buf = Buffer.concat([buf, d]);
      });

      stdout.on('end', function() {
        var key = url.substr(url.lastIndexOf("/")+1) + ":" + suffix;
        var data = {
          ACL: 'public-read',
          Bucket: s3Bucket,
          Key: key,
          Body: buf
        };
        awsClient.putObject(data, function(err, resp) {
          if (err) {
            console.log(err)
          } else {
            cb(null, "blah");
          }
        });
      });
    }
  });
```
which is giving me this
```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
```
