### ISSUE TITLE
Tests fail on OS X with EPIPE Error

### ISSUE THREAD

**Issue by respectTheCode** [aheckmann/gm#209]
It seems to be related to using a buffer for the input.

```
$ npm test

> gm@1.11.1 test /Users/kevin/GitHub/gm
> make test-unit; make test;


All tests passed

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
make: *** [test] Error 8
npm ERR! weird error 2
npm ERR! not ok code 0
```

**Comment by digz6666** [comment]
I installed graphicsmagick and imagemagick to windows but still getting the error.

**Comment by rulonder** [comment]
I get the same error in windows with both graphicsmagick and imagemagick installed. called from gulp-image-resize.

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Error: write EPIPE
    at finish (<path>\node_modules\gulp-image-resize\node_modules\gulp-gm\index.js:38:21)
    at gm.<anonymous> (<path>\node_modules\gulp-image-resize\node_modules\async\lib\async.js:485
:30)
    at gm.emit (events.js:118:17)
    at gm.<anonymous> (<path>\node_modules\gulp-image-resize\node_modules\gulp-gm\node_modules\g
m\lib\getters.js:70:16)
    at Socket.cb (<path>\node_modules\gulp-image-resize\node_modules\gulp-gm\node_modules\gm\lib
\command.js:314:16)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:107:17)
    at onwriteError (_stream_writable.js:317:10)
    at onwrite (_stream_writable.js:335:5)
    at WritableState.onwrite (_stream_writable.js:105:5)
```

**Comment by digz6666** [comment]
@rulonder I restarted my computer and the issue is resolved, try restarting your computer.

**Comment by rulonder** [comment]
Thanks! It worked, good old : "turn it off and on again" :)

**Comment by digz6666** [comment]
@rulonder Seems like our metoer project never refreshed PATH variable, so restart helped.

**Comment by Chaoste** [comment]
I'm experiencing the same problem on MacOSX.
- imagemagick 7.0.8-66
- graphicsmagick 1.3.33
- node 11.12.0
- gm 1.23.1
(Executed by pdf2image 0.5.0)

Restarting PC did not help.
