### ISSUE TITLE
Can't call compare on subclassed gm

### ISSUE THREAD

**Issue by normanrz** [aheckmann/gm#259]
``` js
var gm = require('gm').subClass({ imageMagick: true });
gm.compare(file1, file2, function(){});
```

This does not work for me. `gm.compare` is undefined. I use node v0.10.26 with ImageMagick 6.8.7-7 on OS X 10.9.1.

As a workaround, setting `gm.compare = gm.prototype.compare;` works for me.

**Comment by aliaburas80** [comment]
Hi, did anyone face this error before? 
```
Error: spawn compare ENOENT
    at notFoundError (enoent.js:11:11)
    at verifyENOENT (enoent.js:46:16)
    at ChildProcess.cp.emit (enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

and this is my code

```
var gm = require('gm').subClass({ imageMagick: true });
gm().compare('testImg.jpg', 'testImg-1.jpg', function (err, isEqual, equality, raw, path1, path2) {
    if (err) return handle(err);
    console.log('The images were equal: %s', isEqual);
    console.log('Actual equality: %d', equality);
    console.log(raw);
    console.log(path1, path2);
});
```
