### ISSUE TITLE
Issue with Windows?

### ISSUE THREAD

**Issue by PaulBGD** [aheckmann/gm#352]
I can't imagine what it'd be other than windows, but running just shows me the following error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```
And doing gm version in command prompt shows:
```
C:\Users\paul_000>gm version
GraphicsMagick 1.3.20 2014-08-16 Q16 http://www.GraphicsMagick.org/
Copyright (C) 2002-2014 GraphicsMagick Group.
Additional copyrights and licenses apply to this software.
See http://www.GraphicsMagick.org/www/Copyright.html for details.

Feature Support:
  Native Thread Safe       yes
  Large Files (> 32 bit)   yes
  Large Memory (> 32 bit)  yes
  BZIP                     yes
  DPS                      no
  FlashPix                 no
  FreeType                 yes
  Ghostscript (Library)    no
  JBIG                     yes
  JPEG-2000                yes
  JPEG                     yes
  Little CMS               yes
  Loadable Modules         yes
  OpenMP                   yes (200203)
  PNG                      yes
  TIFF                     yes
  TRIO                     no
  UMEM                     no
  WebP                     yes
  WMF                      yes
  X11                      no
  XML                      yes
  ZLIB                     yes

Windows Build Parameters:

  MSVC Version:            1500
```

**Comment by connor4312** [comment]
Did you reboot after gm installation? Was having the same issue, fixed it for me.

**Comment by PaulBGD** [comment]
Worked, thanks!
