### ISSUE TITLE
GM not working on MAC OS X 10.9.5

### ISSUE THREAD

**Issue by MichalKlacko** [aheckmann/gm#369]
I have installed gm. ```npm install gm``` i have also installed imagemagick and graphicmagick in system.(i try to reinstall it and change the order of installation)
```
brew install imagemagick
brew install graphicsmagick
```
when i try it in cosnole it is working (identify and convert).
But when i run it in nodejs its not working and its giving this error
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

i was trying to run this in node and ist working and show current version of imagemagick
```
var sys = require('sys')    
var exec = require('child_process').exec;
        function puts(error, stdout, stderr) {
                if(error)
                        sys.puts(error);
                if(stderr)
                        sys.puts(stderr);
                sys.puts(stdout);
        }
exec("identify --version", puts);
```
And i'm requiring gm like this
```
    var gm = require('gm').subClass({imageMagick: true});
```

When i deploy it on heroku, its working but not on my local machine (MAC OS X).

Am I doing something wrong or is this a bug?

**Comment by MichalKlacko** [comment]
SOLVED
need to add PATH to enviroment variables (process.env.PATH) with this value bin:node_modules/.bin:/usr/local/bin:/usr/bin:/bin
