### ISSUE TITLE
Having failed tests

### ISSUE THREAD

**Issue by DanMMX** [aheckmann/gm#436]
@rwky when running `npm test` I'm having this:

```
51 $ npm test

> gm@1.18.1 test /Users/dan/Documents/qwertee/gm
> make test-unit; make test;


All tests passed
pending 74
assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: 7.79KB
    at gm.getterfilesize (/Users/dan/Documents/qwertee/gm/test/getterFilesize.js:13:14)
    at gm.emit (events.js:110:17)
    at gm.<anonymous> (/Users/dan/Documents/qwertee/gm/lib/getters.js:82:14)
    at cb (/Users/dan/Documents/qwertee/gm/lib/command.js:318:16)
    at ChildProcess.proc.on.onExit (/Users/dan/Documents/qwertee/gm/lib/command.js:293:9)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
make: *** [test] Error 1
npm ERR! Test failed.  See above for more details.


```

which asks `7.79KB` to be `7792B`, have created a branch fixing that, but I noticed it's passing on travis so maybe wrong on my setup or something, any idea?

**Comment by rwky** [comment]
It's due to your version of Image magick being newer than one the on travis. The tests should compensate for this. Test should pass with any version of gm/convert that run on travis and above.

We need a way of determining the version of gm/convert in use `gm -version` and `convert -version` should do parsing the first line to extract the version string. 

I'm not sure when image magick made the change to break this (you can check the change log if you want) but I'd assume its 6.8 or above so we'd need to adjust the test so if the imagemagick version is > 6.8 then we use the new assert else we use the current one.

**Comment by DanMMX** [comment]
For the record:
ImageMagick 6.9.1-1 Q16 x86_64 2015-04-15
GraphicsMagick 1.3.21 2015-02-28 Q8 http://www.GraphicsMagick.org/

Working on it …
