### ISSUE TITLE
Getting TypeError with Roots

### ISSUE THREAD

**Issue by lucasnantonio** [aheckmann/gm#488]
I'm trying to compile a roots website that uses gm, but at roots watch I'm getting this:

/Users/lucasneumanndeantonio/GitHub/lucas4/node_modules/gm/lib/command.js:227
    proc.stdin.once('error', cb);
              ^

TypeError: Cannot read property 'once' of undefined
  at gm._spawn (/Users/lucasneumanndeantonio/GitHub/lucas4/node_modules/gm/lib/command.js:227:15)
  at /Users/lucasneumanndeantonio/GitHub/lucas4/node_modules/gm/lib/command.js:101:12
  at series (/Users/lucasneumanndeantonio/GitHub/lucas4/node_modules/array-series/index.js:11:36)
  at gm._preprocess (/Users/lucasneumanndeantonio/GitHub/lucas4/node_modules/gm/lib/command.js:177:5)
  at gm.write (/Users/lucasneumanndeantonio/GitHub/lucas4/node_modules/gm/lib/command.js:99:10)
  at [object Object]._onTimeout (/Users/lucasneumanndeantonio/GitHub/lucas4/node_modules/roots-image-pipeline/lib/index.js:302:89)
  at Timer.listOnTimeout (timers.js:92:15)

**Comment by jSchapiroAtTheMelt** [comment]
@lucasnantonio any word on this?

**Comment by artiya4u** [comment]
I have the same problem when I try to manipulate too many images in a single program. I think it forks more processes til it hit OS limit. I have tried "ulimit" but it won't help.

**Comment by useltmann** [comment]
same here after upgrading from fedora 23 to 24. im running my nodejs app inside a docker-container.
As @artiya4u i certainly think it has something to do with os limitations but i cannot figure out which.

what i can say is that selinux seems not to conflict with that issue since my system behaves the same with selinux disabled

**Comment by adambuczynski** [comment]
I have the same error occur on OS X when I tried to process too many images at once. I rewrote the code using bluebird's [`Promise.each`](bluebirdjs.com/docs/api/promise.each.html) to process all the files serially which fixed the issue.
