### ISSUE TITLE
gm fails when performing montage on 100 x 100

### ISSUE THREAD

**Issue by jSchapiroAtTheMelt** [aheckmann/gm#502]
I am trying to read from a directory of greater than 400 jpegs. When it reaches that amount, I get this error. I have a hunch that it is an async issue! 

/Users/jonathanschapiro/Workspace/Mosaiek-Builder/node_modules/gm/lib/command.js:227
    proc.stdin.once('error', cb);
              ^

TypeError: Cannot read property 'once' of undefined
    at gm._spawn (/Users/jonathanschapiro/Workspace/Mosaiek-Builder/node_modules/gm/lib/command.js:227:15)
    at /Users/jonathanschapiro/Workspace/Mosaiek-Builder/node_modules/gm/lib/command.js:101:12
    at series (/Users/jonathanschapiro/Workspace/Mosaiek-Builder/node_modules/gm/node_modules/array-series/index.js:11:36)
    at gm._preprocess (/Users/jonathanschapiro/Workspace/Mosaiek-Builder/node_modules/gm/lib/command.js:177:5)
    at gm.write (/Users/jonathanschapiro/Workspace/Mosaiek-Builder/node_modules/gm/lib/command.js:99:10)
    at Mosaic.gen_avg_rgb (/Users/jonathanschapiro/Workspace/Mosaiek-Builder/Mosaic/Mosaic.js:180:46)
    at moveOn (/Users/jonathanschapiro/Workspace/Mosaiek-Builder/Mosaic/Mosaic.js:158:61)
    at null.<anonymous> (/Users/jonathanschapiro/Workspace/Mosaiek-Builder/Mosaic/Mosaic.js:144:21)
    at wrapper (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by piercus** [comment]
Same issue here,

### Workaround

On my side, i discovered that this issue was linked to the number of async parallel gm call i was doing.

So i fixed it by doing my gm call one by one.

### To go further

From [node documentation](https://nodejs.org/api/child_process.html#child_process_class_childprocess), about stdin it is written that 

> If the child was spawned with stdio[0] set to anything other than 'pipe', then this will be undefined.

Maybe it gives anyone an idea ? 
Is there a problem with spawn when too many parallel call ?

**Comment by Ekzer** [comment]
Same issue here.
I think it is due to the system limitations. 
When node calls "spawn", it does a fork  syscall. So it creates a subprocess. Each subprocess needs a File descriptor and there is a limit about the number of file descriptors and subprocesses.

See the unix command 'ulimit'
And this link : [http://stackoverflow.com/questions/15598266/whats-the-limit-of-spawning-child-processes](url)

**Comment by Ekzer** [comment]
I found a solution.
It is inspired by this answer : http://stackoverflow.com/questions/30274534/nodejs-running-imagemagick-convert-all-images-from-directory

```
const fs = require('fs'),
    async = require('async'),
    gm = require('gm').subClass({imageMagick: true}),
    maxworkers = require('os').cpus().length;

let queue = async.queue(YourFunction, maxworkers);

fs.readdir(YourFolder, function(err, files) {
        files.forEach(function(file) {
            queue.push(ParametersToYourFunction)
        });
    });
}

// your gm stuff
```

**Comment by vzx7** [comment]
There is also a solution through native Promise() and async/await
For me it works like this:
```
fs.readdir(path.resolve(pathImg), async (err, files) => {
  if (err) console.log(err)
  else {
    let arr = []

    files.map(s => {
      arr.push(s.split('.'))
    })

    for (let img of arr) {
      let pathI = path.resolve(pathImg + img[0] + '.' + img[1])
      try {
        await ( function(pathI, art, img) {
          return new Promise((resolve, reject) => {
            gm(pathI)
             .size((err, data) => {
               if (err) {
                 reject(err)
               } else {
                 let pathF = path.resolve(__dirname + '/../public/uploads/page/' + art.elId + '-' + img[0] + '.' + img[1])
                 gm(pathI)
                   .resize(data.width > 748 ? 748 : data.width)
                   .write(pathF, (err) => {
                     if (err) {
                       reject(err)
                      } else {
                       resolve(true)
                      }
                    })
                  }
                })
              })
            })(pathI, art, img)
          } catch (error) { 
              console.log(error);           
          }
        }
    }
})
```
