### ISSUE TITLE
Error: Command failed: 锟斤拷效锟斤拷锟斤拷 - -resize

### ISSUE THREAD

**Issue by OtakuAndFitness** [aheckmann/gm#553]
`C:\Users\suppe\Documents\Visual Studio 2015\Projects\story2.2\story2.2\routes\index.js:37
shed/64_' + req.file.originalname, function (err) { if (err) { throw err } });
                                                                     ^
Error: Command failed: 锟斤拷效锟斤拷锟斤拷 - -resize

    at ChildProcess.module.exports.proto._spawn.proc.on.onExit (C:\Users\suppe\Documents\Visual Studio 2015\Projects\story2.2\story2.2\node_modules\gm\lib\command.js:297:17)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
`
My js file:
`var express = require('express');
var router = express.Router();
var multer = require('multer');
var fs = require('fs');
var gm = require('gm').subClass({ imageMagick: true });
var storage = multer.diskStorage({
    destination: function (req, file, cb) {
        cb(null, 'public/uploads/');
    },
    filename: function (req, file, cb) {
        cb(null, file.originalname);
    }
});
var upload = multer({
    storage: storage, fileFilter: function (req, file, cb) {
        if (file.mimetype !== 'image/png' && file.mimetype !== 'image/jpg' && file.mimetype !== 'image/jpeg') {
            req.fileValidationError = 'goes wrong on the mimetype';
            return cb(null, false, new Error('goes wrong on the mimetype'));
        }
        return cb(null, true);
    }
}).single('myimage');

/* get home page. */
router.get('/', function (req, res) {
    res.render('index', { title: 'express' });
});

router.post('/', function (req, res) {
    upload(req, res, function (err) {
        if (req.fileValidationError) {
            res.send("You didn't upload a valid pic!");
        } else {
            gm(req.file.path).resize(32).write('public/finished/32_' + req.file.originalname, function (err) { if (err) { throw err } });
            gm(req.file.path).resize(64).write('public/finished/64_' + req.file.originalname, function (err) { if (err) { throw err } });
            res.send('successfully!');
        }
    });
});

module.exports = router;
`

**Comment by nicewahson** [comment]
no one can resolve this?
