### ISSUE TITLE
Unhandled error event: Error: Command failed: gm identify: No decode delegate for this image format (/tmp/gmDzkyau). gm identify: Request did not return an image.

### ISSUE THREAD

**Issue by olalonde** [aheckmann/gm#571]
Getting this error occasionally:

```
events.js:160
      throw er; // Unhandled \'error\' event
      ^

Error: Command failed: gm identify: No decode delegate for this image format (/tmp/gmDzkyau).
gm identify: Request did not return an image.

    at ChildProcess.proc.on.onExit (/app/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

How am I supposed to catch the event?

**Comment by omardlhz** [comment]
@olalonde did you figure this out?

**Comment by olalonde** [comment]
I think I ended up adding an `.on('error', () => {})` listener to the stream. Though there's still a bug where some errors are not emitted. And also,  I was getting this error for a PDF file IIRC and PDF is no longer support by graphicsmagick.

Also wrote this utility function:

```
import duplexify from 'duplexify'
import concat from 'concat-stream'
import createError from 'http-errors'
import initDebug from 'debug'
const debug = initDebug('filepunk')

const initStreamCb = ({ output }) => (err, stdout, stderr) => {
  if (err) return output.emit('error', err)

  stdout.on('error', (error) => output.emit('error', error))
  stdout.pipe(output)

  stderr
    .pipe(concat((buf) => {
      const errStr = buf.toString().trim()
      if (errStr) {
        const error = createError(400, errStr)
        output.emit('error', error)
        return
      }
    }))
}

// turns gm calls into a passthrough stream
const wrapGm = async (fn) => {
  const input = new PassThrough()
  const output = new PassThrough()
  const duplex = duplexify(input, output)
  let gm = initGm(input)
  gm = fn(gm) || gm

  output.on('error', debug)

  const streamCb = initStreamCb({ output })
  gm.stream(streamCb)

  return duplex
}

// example usage:
//   const resize = (opts = {}) => {
//     const { width, height, options, filter } = opts
//     return wrapGm(gm => {
//       if (filter) gm.filter(filter)
//       gm.resize(width, height, options)
//     })
//   }
```

**Comment by CRAZYFAKE** [comment]
@olalonde Hello. I got same error in my `Ubuntu 14.04.4 LTS` ,but I had solved this problem by using ImageMagick instead.
```javascript
var gm = require('gm').subClass({ imageMagick: true });
```
I want to know. How does this error happened？Thanks a lot.

**Comment by abratashov** [comment]
I've solved this problem by switching to `imagemagick` https://stackoverflow.com/questions/54653104/error-command-failed-gm-convert-pdf-image-conversion/61778570#61778570
