### ISSUE TITLE
Error: Command failed: gm identify: No decode delegate for this image format 

### ISSUE THREAD

**Issue by olalonde** [aheckmann/gm#590]
When trying to convert a PSD to a PNG, I am getting this error:

```javascript
Error: Command failed: gm identify: No decode delegate for this image format (/var/folders/67/wj749ptn3jlb4_nlf9nphyy00000gn/T/gmegI596).
gm identify: Request did not return an image.

    at ChildProcess.onExit (/Users/olalonde/code/project/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

It is working fine for other image types however. I tried `$ convert -format png test/files/kitty.psd preview.png` in the console and that works.

**Comment by olalonde** [comment]
Code to reproduce:

```
import gm from 'gm'
import { join } from 'path'
import kitchenfile from 'kitchenfile'

const file = kitchenfile(join(__dirname), './files')

const kitty = file('kitty.psd')

gm(kitty.rs()).identify((err, result) => {
  console.log(err)
  console.log(result)
})
```

where `files/kitty.psd` is https://github.com/sindresorhus/file-type/blob/master/fixture/fixture.psd

**Comment by olalonde** [comment]
Narrowed down the problem a bit with `DEBUG=gm`. Now able to reproduce error in console.

This works:

```bash
cat test/files/kitty.psd | identify -
```

but this doesn't

```bash
cat test/files/kitty.psd | /usr/local/bin/gm identify -
```

So I guess `identify` is imagemagick and not graphicsmagick. And I suppose my graphicsmagick installation (brew install graphicsmagick) does not support PSDs?

**Comment by olalonde** [comment]
Opened issue on Homebrew: https://github.com/Homebrew/homebrew-core/issues/6072

**Comment by JustinYi922** [comment]
您好。我在unbutu上也遇到了这个问题。在Mac上，运行确实正常的。
