### ISSUE TITLE
Command Failed Error

### ISSUE THREAD

**Issue by crosofg** [aheckmann/gm#591]
I am getting this error
```
F:\Technology\Learning\Projects\faya\whispering-sierra-69547\tests>node gm.js
{ '0':
   { Error: Command failed:
       at ChildProcess.onExit (F:\Technology\Learning\Projects\faya\whispering-sierra-69547\node_modules\gm\lib\command.js:301:17)
       at emitTwo (events.js:106:13)
       at ChildProcess.emit (events.js:191:7)
       at ChildProcess.cp.emit (F:\Technology\Learning\Projects\faya\whispering-sierra-69547\node_modules\cross-spawn\lib\enoent.js:40:29)
       at maybeClose (internal/child_process.js:877:16)
       at Socket.<anonymous> (internal/child_process.js:334:11)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at Pipe._handle.close [as _onclose] (net.js:493:12) code: 1, signal: null },
  '1': '',
  '2': '',
  '3': 'gm "convert" "F:/Technology/Learning/Projects/faya/whispering-sierra-69547/tests/cat.jpg" "-blur" "19x10" "F:/Technology/Learning/Projects/faya/whispering-sierra-69547/tests/blur.jpg"' }
```

**Comment by ossso** [comment]
Try `Bash on Windows`

**Comment by hassannomani** [comment]
Facing the same issue.
