### ISSUE TITLE
gm convert: Read Exception

### ISSUE THREAD

**Issue by alexcroox** [aheckmann/gm#612]
GraphicsMagick 1.3.23 (fresh install via brew)
OS X 10.12
Node v6.2.1

I'm trying to do a basic `identify` and `crop`, both fail. However `size` does work.

```
var fs = require('fs'),
    gm = require('gm');

gm('test.png').identify(function(err, details) {

    if(!err) 
        console.log('Details', details);
    else
        console.log('Error getting image details', err);
});

gm('test.png').size(function(err, size) {

    if(!err)
        console.log('Size', size);
    else
        console.log('Error getting size', err);
});

gm('test.png')
    .crop(256, 256, 0, 0)
    .write('extract.png', function(err) {
        if (!err)
            console.log('Saved');
        else
            console.log('Error cropping', err);
    })
```

The output is:

```
node index.js

Size { width: 5120, height: 5120 }

Error getting image details { Error: Command failed: gm identify: Read Exception (test.png).
gm identify: Request did not return an image.

    at ChildProcess.proc.on.onExit (/Users/alex/Projects/tile-generator/nodejs/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5) code: 1, signal: null }


Error cropping { Error: Command failed: gm convert: Read Exception (test.png).

    at ChildProcess.proc.on.onExit (/Users/alex/Projects/tile-generator/nodejs/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5) code: 1, signal: null }
```

As you can see size works fine but identify and crop both fail with `Error: Command failed: gm convert: Read Exception (test.png)`

**Comment by alexcroox** [comment]
Turns out the png I had was technically corrupt (despite loading OK in all applications I passed it to).

Resolved with `pngjs` by first re-saving it with:

```
var PNG = require('pngjs').PNG;

var data = fs.readFileSync('test.png');
var png = PNG.sync.read(data);
var buffer = PNG.sync.write(png);
fs.writeFileSync('fixed.png', buffer);
```
