### ISSUE TITLE
"Error: Stream yields empty buffer" when using dissolve()

### ISSUE THREAD

**Issue by PassTheMayo** [aheckmann/gm#673]
Hello. I just recently started using Graphics Magick. I installed using `npm i gm` and did the `sudo apt-get install graphics-magick` command, and it works fine. Every method seems to work except dissolve(). Here's my code:
```js
gm(body.body).dissolve(50).toBuffer((error, buffer) => {
    if (error) return console.error(error);
    // do stuff
});```
I am getting the following error:
```
Error: Stream yields empty buffer
  at Socket.<anonymous> (/root/bots/prisma/node_modules/gm/lib/command.js:57:17)
  at emitNone (events.js:110:20)
  at Socket.emit (events.js:207:7)
  at endReadableNT (_stream_readable.js:1059:12)
  at _combinedTickCallback (internal/process/next_tick.js:138:11)
  at process._tickCallback (internal/process/next_tick.js:180:9)```
Can anyone help?

**Comment by albertyou2** [comment]
+1

**Comment by luck2011** [comment]
same here after using ```.autoOrient()```

**Comment by luyufa** [comment]
+1 help

**Comment by sharstream** [comment]
1+ help from here. After include `<?xml><svg></svg>`, I'm getting Stream yields empty buffer. Any thoughts, how convert svg to buffer with node/gm?
