### ISSUE TITLE
Command failed: dyld: Library not loaded: /ImageMagick-7.0.7/lib/libMagickCore-7.Q16HDRI.5.dylib

### ISSUE THREAD

**Issue by Mttylzq** [aheckmann/gm#723]
myjs code is bellow:

gm(__dirname + '/1.jpg')
  .options({imageMagick: true}) // на mac почему-то очень долго работает
  // .noProfile()
  .write(__dirname + '/resample.jpg', function(err){
    if (err) return console.dir(arguments)
    console.log(this.outname + " created  ::  " + arguments[3])
  })

console error info 

{ '0': 
   { Error: Command failed: dyld: Library not loaded: /ImageMagick-7.0.7/lib/libMagickCore-7.Q16HDRI.5.dylib
     Referenced from: /Users/luzq/develop/ImageMagick-7.0.7/bin/convert
     Reason: image not found
   
       at ChildProcess.onExit (/Users/luzq/projects/qxClient/node_modules/gm/lib/command.js:301:17)
       at emitTwo (events.js:106:13)
       at ChildProcess.emit (events.js:191:7)
       at maybeClose (internal/child_process.js:920:16)
       at Socket.<anonymous> (internal/child_process.js:351:11)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at Pipe._handle.close [as _onclose] (net.js:509:12) code: null, signal: 'SIGABRT' },
  '1': '',
  '2': 'dyld: Library not loaded: /ImageMagick-7.0.7/lib/libMagickCore-7.Q16HDRI.5.dylib\n  Referenced from: /Users/luzq/develop/ImageMagick-7.0.7/bin/convert\n  Reason: image not found\n',
  '3': 'convert "/Users/luzq/projects/qxClient/src/1.jpg" "/Users/luzq/projects/qxClient/src/resample.jpg"' }

**Comment by borriej** [comment]
Same issue here...
