### ISSUE TITLE
GM .write not making file

### ISSUE THREAD

**Issue by Dream-cake** [aheckmann/gm#741]
Hi i have been trying to do this and its not working..

`const gm = require('gm')

const fs = require('fs')
const Discord = require("discord.js");

module.exports.run = async (bot, message, args) => {
    if(!args[0]) return message.channel.send("please say something for this meme")

    
        
    
    let e = args.join(" ")

  gm('hb.jpg')
    .stroke("#000000")
    .font("Arial", 25)
    .drawText(18, 104, e)
    .write('Out.png', function (err) {
      if(err) return console.log(err);
        

     message.channel.send({
            files: [
               "Out.png"
            ]
        })
    })
    
}

module.exports.help = {
    name: "trump"
}`

and its not making the file
![hb](https://user-images.githubusercontent.com/31389391/43658373-b564fd86-9726-11e8-8724-27aa0892bacf.jpg)

idk why the error is
`Error: Could not execute GraphicsMagick/ImageMagick: gm "convert" "hb.jpg" "-stroke" "#000000" "-pointsize" "25" "-font" "Arial" "-draw" "text 18,104 \"dopeaaa\"" "Out.png" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (C:\Users\thesp\Desktop\DreamingBot\node_modules\gm\lib\command.js:232:12)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at ChildProcess.cp.emit (C:\Users\thesp\Desktop\DreamingBot\node_modules\cross-spawn\lib\enoent.js:36:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
`
but i have gm install and updated

**Comment by gloorgon** [comment]
hey look

**Comment by Dream-cake** [comment]
?

**Comment by gloorgon** [comment]
do you have the binaries installed?
