### ISSUE TITLE
unrecognized option

### ISSUE THREAD

**Issue by tokelpl** [aheckmann/gm#751]
` { Error: Command failed: convert: unrecognized option `-resize 50%' @ error/convert.c/ConvertImageCommand/2652.

    at ChildProcess.onExit (/home/tomekb530/fbBot/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12) code: 1, signal: null }
`

`gm('./cache/cache.png').command('convert').in('-resize 50%').write('asdf.png',(err)=>{
  if(!err){console.log('ss')}else{console.log(err)}
})`

**Comment by tokelpl** [comment]
iam using imagemagick btw
