### ISSUE TITLE
Help required

### ISSUE THREAD

**Issue by tshradheya** [aheckmann/gm#753]
Env: Using 1.4.1 gm

Crashing on this line multiple times:

```
/srv/app/node_modules/gm/lib/convenience/autoOrient.js:26
        var transforms = exifTransforms[orientation.toLowerCase()];
                                                    ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at gm.<anonymous> (/srv/app/node_modules/gm/lib/convenience/autoOrient.js:26:53)
    at gm.<anonymous> (/srv/app/node_modules/gm/lib/getters.js:38:18)
    at ChildProcess.<anonymous> (/srv/app/node_modules/gm/lib/getters.js:145:23)
    at ChildProcess.onExit (/srv/app/node_modules/gm/lib/command.js:224:18)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

**Comment by tshradheya** [comment]
@aheckmann @jonathanong Would appreciate any input
