### ISSUE TITLE
Node 10 error

### ISSUE THREAD

**Issue by Daxito** [aheckmann/gm#791]
Hi, I am getting this error when using Node 10, any suggestions? Thanks!!

 Error: Could not execute GraphicsMagick/ImageMagick: identify "-ping" "-format" "%wx%h" "-" this most likely means the gm/convert binaries can't be found
at ChildProcess.<anonymous> (/var/task/node_modules/gm/lib/command.js:232:12)
at ChildProcess.emit (events.js:198:13)
at ChildProcess.EventEmitter.emit (domain.js:448:20)
at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
at onErrorNT (internal/child_process.js:415:16)
at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by mattcwill** [comment]
If you happen to be using AWS Lambda and recently changed from the nodejs8.10 runtime to the nodejs10.x runtime, it's because the underlying Amazon Linux 2 execution environment for nodejs10.x no longer includes the ImageMagick binaries. See [this thread](https://forums.aws.amazon.com/thread.jspa?messageID=906619&tstart=0) on the AWS forums for more information. I ended up creating a layer with the ImageMagick binaries to use with my lambda function and no longer get the error.

**Comment by setu1421** [comment]
@mattcwill , Can you please help me out how to create a layer with the ImageMagick binaries to use with lambda function. I am facing the same error.

**Comment by se-bastiaan** [comment]
Try https://github.com/serverlesspub/imagemagick-aws-lambda-2.git

**Comment by mattcwill** [comment]
> Try https://github.com/serverlesspub/imagemagick-aws-lambda-2.git

Yes this is what I used as well.

**Comment by setu1421** [comment]
I could make it work by adding a layer in the aws lambda
